name: nexoboard
description: "A new Flutter project for NexaBoard."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- CONFIGURACIÓN DE FIREBASE ---
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2
  firebase_messaging: ^16.3.0

  # --- ARQUITECTURA Y GESTIÓN DE ESTADO ---
  get_it: ^9.2.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1

  # --- SISTEMA DE ANIMACIONES ---
  flutter_animate: ^4.5.0
  animations: ^2.0.11

  # --- UTILIDADES E INTEGRACIONES ---
  intl: ^0.20.2
  http: ^1.2.1
  image_picker: ^1.0.7
  file_picker: ^11.0.2
  lucide_icons_flutter: ^3.1.14+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # --- REGISTRO DE TIPOGRAFÍAS ---
  fonts:
    - family: CyGrotesk
      fonts:
        - asset: assets/fonts/CyGrotesk-KeyBold.otf
          weight: 700

    - family: Lovera
      fonts:
        - asset: assets/fonts/Lovera Personal Use Only.otf
          weight: 400