// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoAmuKDeQzgR9eBM5okPJTs6PUgwogRZQ',
    appId: '1:400993832390:web:38f46ab7ef8d92ab17b6c7',
    messagingSenderId: '400993832390',
    projectId: 'nexo-board',
    authDomain: 'nexo-board.firebaseapp.com',
    storageBucket: 'nexo-board.firebasestorage.app',
    measurementId: 'G-04B70HTT37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZsF3cI3YBO7qRb81CAuqCznVjOU3J6M',
    appId: '1:400993832390:android:2a953efbb946be5e17b6c7',
    messagingSenderId: '400993832390',
    projectId: 'nexo-board',
    storageBucket: 'nexo-board.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY0s4UVFR9V7ONhdT0BuUidTagwmmlXn8',
    appId: '1:400993832390:ios:d4bfbe4351dc8f9717b6c7',
    messagingSenderId: '400993832390',
    projectId: 'nexo-board',
    storageBucket: 'nexo-board.firebasestorage.app',
    iosBundleId: 'com.example.nexoboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY0s4UVFR9V7ONhdT0BuUidTagwmmlXn8',
    appId: '1:400993832390:ios:d4bfbe4351dc8f9717b6c7',
    messagingSenderId: '400993832390',
    projectId: 'nexo-board',
    storageBucket: 'nexo-board.firebasestorage.app',
    iosBundleId: 'com.example.nexoboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoAmuKDeQzgR9eBM5okPJTs6PUgwogRZQ',
    appId: '1:400993832390:web:3e963083b5e7e76117b6c7',
    messagingSenderId: '400993832390',
    projectId: 'nexo-board',
    authDomain: 'nexo-board.firebaseapp.com',
    storageBucket: 'nexo-board.firebasestorage.app',
    measurementId: 'G-RGHBWYTQNG',
  );
}
